services:
  flask-server:
    container_name: flask-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=server.py
    volumes:
      - ./data:/usr/src/app/data
