import { createSystem, defaultConfig, defineConfig } from '@chakra-ui/react';

const varRoot = ':host';

const config = defineConfig({
  cssVarsRoot: varRoot,
  conditions: {
    light: `${varRoot} &, .light &`,
  },
  preflight: { scope: varRoot },
  globalCss: {
    [varRoot]: defaultConfig.globalCss?.html ?? {},
  },
  theme: {
    tokens: {
      sizes: {
        // Numeric sizes
        '1': { value: '4px' },
        '2': { value: '8px' },
        '3': { value: '12px' },
        '4': { value: '16px' },
        '5': { value: '20px' },
        '6': { value: '24px' },
        '7': { value: '28px' },
        '8': { value: '32px' },
        '9': { value: '36px' },
        '10': { value: '40px' },
        '11': { value: '44px' },
        '12': { value: '48px' },
        '14': { value: '56px' },
        '16': { value: '64px' },
        '20': { value: '80px' },
        '24': { value: '96px' },
        '28': { value: '112px' },
        '32': { value: '128px' },
        '36': { value: '144px' },
        '40': { value: '160px' },
        '44': { value: '176px' },
        '48': { value: '192px' },
        '52': { value: '208px' },
        '56': { value: '224px' },
        '60': { value: '240px' },
        '64': { value: '256px' },
        '72': { value: '288px' },
        '80': { value: '320px' },
        '96': { value: '384px' },
        // Fractional sizes
        '0.5': { value: '2px' },
        '1.5': { value: '6px' },
        '2.5': { value: '10px' },
        '3.5': { value: '14px' },
        '4.5': { value: '18px' },
        // T-shirt sizes
        '3xs': { value: '224px' },
        '2xs': { value: '256px' },
        xs: { value: '320px' },
        sm: { value: '384px' },
        md: { value: '448px' },
        lg: { value: '512px' },
        xl: { value: '576px' },
        '2xl': { value: '672px' },
        '3xl': { value: '768px' },
        '4xl': { value: '896px' },
        '5xl': { value: '1024px' },
        '6xl': { value: '1152px' },
        '7xl': { value: '1280px' },
        '8xl': { value: '1440px' },
      },
      spacing: {
        // Numeric spacing
        '1': { value: '4px' },
        '2': { value: '8px' },
        '3': { value: '12px' },
        '4': { value: '16px' },
        '5': { value: '20px' },
        '6': { value: '24px' },
        '7': { value: '28px' },
        '8': { value: '32px' },
        '9': { value: '36px' },
        '10': { value: '40px' },
        '11': { value: '44px' },
        '12': { value: '48px' },
        '14': { value: '56px' },
        '16': { value: '64px' },
        '20': { value: '80px' },
        '24': { value: '96px' },
        '28': { value: '112px' },
        '32': { value: '128px' },
        '36': { value: '144px' },
        '40': { value: '160px' },
        '44': { value: '176px' },
        '48': { value: '192px' },
        '52': { value: '208px' },
        '56': { value: '224px' },
        '60': { value: '240px' },
        '64': { value: '256px' },
        '72': { value: '288px' },
        '80': { value: '320px' },
        '96': { value: '384px' },
        // Fractional spacing
        '0.5': { value: '2px' },
        '1.5': { value: '6px' },
        '2.5': { value: '10px' },
        '3.5': { value: '14px' },
        '4.5': { value: '18px' },
      },
      fontSizes: {
        '2xs': { value: '10px' },
        xs: { value: '12px' },
        sm: { value: '14px' },
        md: { value: '16px' },
        lg: { value: '18px' },
        xl: { value: '20px' },
        '2xl': { value: '24px' },
        '3xl': { value: '30px' },
        '4xl': { value: '36px' },
        '5xl': { value: '48px' },
        '6xl': { value: '60px' },
        '7xl': { value: '72px' },
        '8xl': { value: '96px' },
        '9xl': { value: '128px' },
      },
      radii: {
        none: { value: '0' },
        '2xs': { value: '1px' },
        xs: { value: '2px' },
        sm: { value: '4px' },
        md: { value: '6px' },
        lg: { value: '8px' },
        xl: { value: '12px' },
        '2xl': { value: '16px' },
        '3xl': { value: '24px' },
        '4xl': { value: '32px' },
        full: { value: '9999px' },
      },
    },
  },
});

export const system = createSystem(defaultConfig, config);
