name: Publish Server to Dockerhub

on:
  push:
    tags:
      - '**' # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push adaptive-ui image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            willtrem/self-hosted-wishlist-server:${{ steps.tag.outputs.VERSION }}
            willtrem/self-hosted-wishlist-server:latest
          context: ./server-flask
          file: ./server-flask/prod.Dockerfile
          # cache-from: |
          #   type=gha
          #   type=registry,ref=willtrem/self-hosted-wishlist-server:latest
          # cache-to: type=gha,mode=max
